# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

 pod 'Firebase', '>= 2.5.1'
 pod 'Hakuba'
 pod "PagingMenuController"
 pod 'ALCameraViewController'
 pod 'Bluetonium'

 # CordovaLib Dependency Pod
pod 'Cordova'
# Cordova Core Plugin Dependency Pod References

pod 'CordovaPlugin-console'
pod 'cordova-plugin-camera'
pod 'cordova-plugin-contacts'
pod 'cordova-plugin-device'
pod 'cordova-plugin-device-orientation'
pod 'cordova-plugin-device-motion'
pod 'cordova-plugin-globalization'
pod 'cordova-plugin-geolocation'
pod 'cordova-plugin-file'
pod 'cordova-plugin-media-capture'
pod 'cordova-plugin-network-information'
pod 'cordova-plugin-splashscreen'
pod 'cordova-plugin-inappbrowser'
pod 'cordova-plugin-file-transfer'
pod 'cordova-plugin-statusbar'
pod 'cordova-plugin-vibration'
pod 'cordova-plugin-wkwebview-engine'

# The following includes the PhoneGap iOS Platform Project Template for a quick start
pod 'phonegap-ios-template'

target 'MOswift' do

end

target 'MOswiftTests' do

end

target 'MOswiftUITests' do

end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
